source 'https://github.com/forestfsl/SegmentSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'AppStoreKit_Example' do
  pod 'AppStoreKit', :path => '../'
  pod 'CommonKit', '~> 0.0.1'
  pod 'SLCategory', '~> 0.0.1'
  pod 'SLWebEngine','~> 0.0.6'
  pod 'CTMediatoKit','~> 0.0.4'

#  target 'AppStoreKit_Tests' do
#    inherit! :search_paths
#
#
#  end
end
